# Generated by Django 6.0.5 on 2026-06-02 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0011_contact_avatar_lead_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of items purchased')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit_price)', max_digits=12)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Expected or actual delivery date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', help_text='Current status of the purchase', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase')),
                ('size', models.CharField(blank=True, help_text='Size (e.g., S, M, L, XL for clothes)', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color or variation', max_length=100)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (e.g., Credit Card, Cash, etc.)', max_length=100)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice/Receipt number', max_length=100, unique=True)),
                ('currency', models.ForeignKey(help_text='Currency of the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='crm.currency')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_department_related', to='auth.group', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('product', models.ForeignKey(help_text='Product/Clothes being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='crm.product')),
                ('user', models.ForeignKey(help_text='User who made the purchase', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['user', '-purchase_date'], name='crm_purchas_user_id_d91753_idx'), models.Index(fields=['product', '-purchase_date'], name='crm_purchas_product_74877e_idx'), models.Index(fields=['status'], name='crm_purchas_status_abfb88_idx')],
            },
        ),
    ]
